### ISSUE TITLE
bug: Switching to any region then back 7 seas crashes app

### ISSUE THREAD

**Issue by Lazylllama** [hackclub/high-seas#1055]
If you select a region in the shop, Eg. EU then switch back to all the 7 seas the application crashes.

**Error Message**
```ts
277-a53502bee94c80ca.js:19 NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at a2 (fd9d1056-ed008aabe7b29b28.js:1:76981)
    at a6 (fd9d1056-ed008aabe7b29b28.js:1:78565)
    at a5 (fd9d1056-ed008aabe7b29b28.js:1:81367)
    at a6 (fd9d1056-ed008aabe7b29b28.js:1:78715)
    at a5 (fd9d1056-ed008aabe7b29b28.js:1:78840)
    at a6 (fd9d1056-ed008aabe7b29b28.js:1:78715)
    at a5 (fd9d1056-ed008aabe7b29b28.js:1:78840)
    at a6 (fd9d1056-ed008aabe7b29b28.js:1:78715)
    at a5 (fd9d1056-ed008aabe7b29b28.js:1:81367)
    at a6 (fd9d1056-ed008aabe7b29b28.js:1:78715)
    at a5 (fd9d1056-ed008aabe7b29b28.js:1:78840)
    at a6 (fd9d1056-ed008aabe7b29b28.js:1:78715)
    at a5 (fd9d1056-ed008aabe7b29b28.js:1:81367)
    at a6 (fd9d1056-ed008aabe7b29b28.js:1:78715)
    at a5 (fd9d1056-ed008aabe7b29b28.js:1:78840)
    at a6 (fd9d1056-ed008aabe7b29b28.js:1:78715)
    at a5 (fd9d1056-ed008aabe7b29b28.js:1:81367)
    at a6 (fd9d1056-ed008aabe7b29b28.js:1:78715)
    at a5 (fd9d1056-ed008aabe7b29b28.js:1:84068)
    at a6 (fd9d1056-ed008aabe7b29b28.js:1:78715)
    at a5 (fd9d1056-ed008aabe7b29b28.js:1:78840)
    at a6 (fd9d1056-ed008aabe7b29b28.js:1:78715)
    at a5 (fd9d1056-ed008aabe7b29b28.js:1:78840)
    at a6 (fd9d1056-ed008aabe7b29b28.js:1:78715)
    at a5 (fd9d1056-ed008aabe7b29b28.js:1:81367)
    at a6 (fd9d1056-ed008aabe7b29b28.js:1:78715)
    at a5 (fd9d1056-ed008aabe7b29b28.js:1:81367)
    at a6 (fd9d1056-ed008aabe7b29b28.js:1:78715)
    at a5 (fd9d1056-ed008aabe7b29b28.js:1:84068)
    at a6 (fd9d1056-ed008aabe7b29b28.js:1:78715)
    at a5 (fd9d1056-ed008aabe7b29b28.js:1:78840)
    at a6 (fd9d1056-ed008aabe7b29b28.js:1:78715)
    at a5 (fd9d1056-ed008aabe7b29b28.js:1:78840)
    at a6 (fd9d1056-ed008aabe7b29b28.js:1:78715)
    at a5 (fd9d1056-ed008aabe7b29b28.js:1:81367)
    at a6 (fd9d1056-ed008aabe7b29b28.js:1:78715)
    at a5 (fd9d1056-ed008aabe7b29b28.js:1:78840)
    at a6 (fd9d1056-ed008aabe7b29b28.js:1:78715)
    at a5 (fd9d1056-ed008aabe7b29b28.js:1:78840)
    at a6 (fd9d1056-ed008aabe7b29b28.js:1:78715)
    at a5 (fd9d1056-ed008aabe7b29b28.js:1:78840)
    at a6 (fd9d1056-ed008aabe7b29b28.js:1:78715)
    at a5 (fd9d1056-ed008aabe7b29b28.js:1:78840)
    at a6 (fd9d1056-ed008aabe7b29b28.js:1:78715)
    at a5 (fd9d1056-ed008aabe7b29b28.js:1:81367)
    at a6 (fd9d1056-ed008aabe7b29b28.js:1:78715)
    at a5 (fd9d1056-ed008aabe7b29b28.js:1:81367)
    at a6 (fd9d1056-ed008aabe7b29b28.js:1:78715)
    at a5 (fd9d1056-ed008aabe7b29b28.js:1:78840)
    at a6 (fd9d1056-ed008aabe7b29b28.js:1:78715)
(anonymous) @ 277-a53502bee94c80ca.js:19
window.console.error @ 277-a53502bee94c80ca.js:1
overrideMethod @ hook.js:608
l_ @ fd9d1056-ed008aabe7b29b28.js:1
n.callback @ fd9d1056-ed008aabe7b29b28.js:1
nB @ fd9d1056-ed008aabe7b29b28.js:1
nV @ fd9d1056-ed008aabe7b29b28.js:1
aq @ fd9d1056-ed008aabe7b29b28.js:1
aY @ fd9d1056-ed008aabe7b29b28.js:1
a9 @ fd9d1056-ed008aabe7b29b28.js:1
aY @ fd9d1056-ed008aabe7b29b28.js:1
a9 @ fd9d1056-ed008aabe7b29b28.js:1
aY @ fd9d1056-ed008aabe7b29b28.js:1
a9 @ fd9d1056-ed008aabe7b29b28.js:1
aY @ fd9d1056-ed008aabe7b29b28.js:1
a9 @ fd9d1056-ed008aabe7b29b28.js:1
aY @ fd9d1056-ed008aabe7b29b28.js:1
a9 @ fd9d1056-ed008aabe7b29b28.js:1
aY @ fd9d1056-ed008aabe7b29b28.js:1
a9 @ fd9d1056-ed008aabe7b29b28.js:1
aY @ fd9d1056-ed008aabe7b29b28.js:1
a9 @ fd9d1056-ed008aabe7b29b28.js:1
aY @ fd9d1056-ed008aabe7b29b28.js:1
a9 @ fd9d1056-ed008aabe7b29b28.js:1
aY @ fd9d1056-ed008aabe7b29b28.js:1
(anonymous) @ fd9d1056-ed008aabe7b29b28.js:1
is @ fd9d1056-ed008aabe7b29b28.js:1
nb @ fd9d1056-ed008aabe7b29b28.js:1
o6 @ fd9d1056-ed008aabe7b29b28.js:1
iV @ fd9d1056-ed008aabe7b29b28.js:1
sU @ fd9d1056-ed008aabe7b29b28.js:1
uO @ fd9d1056-ed008aabe7b29b28.js:1
uM @ fd9d1056-ed008aabe7b29b28.js:1
n @ 277-a53502bee94c80ca.js:19````

**Comment by Gitstar-OC** [comment]
Let me check it.

**Comment by Gitstar-OC** [comment]
Nope it is working fine from my side, and no logs can be found. Closing it as of now. Please upload a video or add more info. Try clearing cache and cookies too.

**Comment by Lazylllama** [comment]
Reopen, this has been an issue for months. Just haven't made an issue til now. 

[https://cloud-1ntq0lx2z-hack-club-bot.vercel.app/02024-12-31_14-31-32.mp4](https://cloud-1ntq0lx2z-hack-club-bot.vercel.app/02024-12-31_14-31-32.mp4)

**Comment by Gitstar-OC** [comment]
Oh, It does not look like a problem on my device @BudzioT could you cross check it ?

**Comment by Lazylllama** [comment]
Why are you immediately closing the issue?

**Comment by Gitstar-OC** [comment]
Wait, I didn't have to open the issue it was opened by mistake! It will be opened after confirmation or I think it is maybe a device issue.

**Comment by BudzioT** [comment]
No matter how much and fast I click, I can't recreate it

**Comment by Lazylllama** [comment]
Sold my mac, using windows PC now. Problem doesn't exist.
